# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
      brew_packages: libgit2
  allow_failures:
    - os: osx


r_github_packages:
  - iNZightVIT/iNZightTools@dev
  - iNZightVIT/iNZightPlots@dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown -R $(whoami) /usr/local/share; fi

after_success:
  - Rscript -e 'covr::codecov()'
