# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

r:
  - oldrel
  - release
  - devel

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R
